const PROGRAM = {
  title: "Guitar Shred Program",
  subtitle: "Livello intermedio-avanzato — Target: Another Day sestine",
  target: "Another Day – Dream Theater (J. Petrucci) — parte veloce 3NPC sestine",

  principles: [
    { title: "Regola del Metronomo", text: "Non saltare BPM. Ogni salto è di 4 BPM massimo. Se una sessione va male, torna a -8 BPM senza sensi di colpa — è parte del processo." },
    { title: "Regola del 95%", text: "Aumenta il BPM solo quando l'esercizio suona pulito al 95% per 3 ripetizioni consecutive. Una volta ogni tanto va bene. Due volte su tre no." },
    { title: "Regola della Registrazione", text: "Registrati ogni settimana. A 100 BPM tutto sembra pulito. All'ascolto critico si sentono le note soffocate, i cambi di corda irregolari, il vibrato meccanico." },
    { title: "Regola del Rilassamento", text: "Velocità e tensione sono nemici. Se dopo 10 minuti il braccio è teso: fermati, scrollalo, ricomincia. La tensione limita il BPM e causa infortuni." },
    { title: "Regola delle Sestine", text: "Le sestine di trentaduesimi di Another Day NON si imparano suonando Another Day. Si imparano con esercizi isolati a BPM crescente, poi si applica al brano." },
  ],

  sessionStructure: [
    { phase: "Riscaldamento", duration: "5 min", content: "Cromatici lenti + stretching passivo + 2 min picking lento molto controllato" },
    { phase: "Tecnica principale", duration: "15-20 min", content: "Esercizio focus con metronomo — metodo a scatti o progressione lineare" },
    { phase: "Applicazione musicale", duration: "5-10 min", content: "Frase complessa / assolo / improvvisazione su backing track" },
  ],

  months: [
    {
      id: 1,
      title: "Mese 1 — Rottura del Muro dei 100 BPM",
      objective: "Portare il picking 3NPC da 100 a 120 BPM sedicesimi. Consolidare pick slanting e sincronizzazione a velocità medio-alta. Eliminare le imprecisioni nei cambi di corda.",
      weeks: [
        {
          id: "1-2",
          title: "Settimane 1-2 — Pick Slanting ad alta velocità",
          exercises: [
            {
              id: "PS-A",
              title: "Escape stroke UPS — 3NPC ascendente veloce",
              technique: "Pick Slanting",
              bpm: 100,
              bpmTarget: 120,
              tab: [
                "e|--5--7--8--5--7--8--|",
                "B|--5--7--8--5--7--8--|",
                "G|--5--7--9--5--7--9--|",
                "D|--5--7--9--5--7--9--|",
                "A|--5--7--8--5--7--8--|",
                "E|--5--7--8--5--7--8--|",
              ],
              tip: "Ascendendo il cambio di corda avviene dopo un DOWN stroke — usa UPS. Focalizzati solo sul cambio di corda: deve essere invisibile, senza micro-pausa. Se senti un click o un silenzio al cambio, il plettro si sta incagliando.",
              notes: [
                { string: 6, fret: 5, duration: "16" }, { string: 6, fret: 7, duration: "16" }, { string: 6, fret: 8, duration: "16" },
                { string: 5, fret: 5, duration: "16" }, { string: 5, fret: 7, duration: "16" }, { string: 5, fret: 8, duration: "16" },
                { string: 4, fret: 5, duration: "16" }, { string: 4, fret: 7, duration: "16" }, { string: 4, fret: 9, duration: "16" },
                { string: 3, fret: 5, duration: "16" }, { string: 3, fret: 7, duration: "16" }, { string: 3, fret: 9, duration: "16" },
                { string: 2, fret: 5, duration: "16" }, { string: 2, fret: 7, duration: "16" }, { string: 2, fret: 8, duration: "16" },
                { string: 1, fret: 5, duration: "16" }, { string: 1, fret: 7, duration: "16" }, { string: 1, fret: 8, duration: "16" },
              ],
            },
            {
              id: "PS-B",
              title: "Escape stroke DPS — 3NPC discendente veloce",
              technique: "Pick Slanting",
              bpm: 100,
              bpmTarget: 120,
              tab: [
                "e|--8--7--5--8--7--5--|",
                "B|--8--7--5--8--7--5--|",
                "G|--9--7--5--9--7--5--|",
                "D|--9--7--5--9--7--5--|",
                "A|--8--7--5--8--7--5--|",
                "E|--8--7--5--8--7--5--|",
              ],
              tip: "Discendendo il cambio avviene dopo un UP stroke — usa DPS. Molti chitarristi sono più deboli in discesa: se noti asimmetria tra salita e discesa, dedica il doppio del tempo a questo esercizio.",
              notes: [
                { string: 1, fret: 8, duration: "16" }, { string: 1, fret: 7, duration: "16" }, { string: 1, fret: 5, duration: "16" },
                { string: 2, fret: 8, duration: "16" }, { string: 2, fret: 7, duration: "16" }, { string: 2, fret: 5, duration: "16" },
                { string: 3, fret: 9, duration: "16" }, { string: 3, fret: 7, duration: "16" }, { string: 3, fret: 5, duration: "16" },
                { string: 4, fret: 9, duration: "16" }, { string: 4, fret: 7, duration: "16" }, { string: 4, fret: 5, duration: "16" },
                { string: 5, fret: 8, duration: "16" }, { string: 5, fret: 7, duration: "16" }, { string: 5, fret: 5, duration: "16" },
                { string: 6, fret: 8, duration: "16" }, { string: 6, fret: 7, duration: "16" }, { string: 6, fret: 5, duration: "16" },
              ],
            },
            {
              id: "PS-C",
              title: "TWPS — Scala completa su e giù senza fermarsi",
              technique: "Pick Slanting",
              bpm: 95,
              bpmTarget: 115,
              tab: [
                "e|--5-7-8-5-7-8-8-7-5-8-7-5--|",
                "B|--5-7-8-5-7-8-8-7-5-8-7-5--|",
                "G|--5-7-9-5-7-9-9-7-5-9-7-5--|",
                "D|--5-7-9-5-7-9-9-7-5-9-7-5--|",
                "A|--5-7-8-5-7-8-8-7-5-8-7-5--|",
                "E|--5-7-8-5-7-8-8-7-5-8-7-5--|",
              ],
              tip: "Il Two Way Pick Slanting: cambi inclinazione automaticamente ad ogni cambio di direzione. Non pensarci consciamente — lascia che venga da solo con la ripetizione. Il punto critico è la inversione in cima (e) e in fondo (E): lì il plettro deve cambiare slant istantaneamente.",
              notes: [
                { string: 6, fret: 5, duration: "16" }, { string: 6, fret: 7, duration: "16" }, { string: 6, fret: 8, duration: "16" },
                { string: 5, fret: 5, duration: "16" }, { string: 5, fret: 7, duration: "16" }, { string: 5, fret: 8, duration: "16" },
                { string: 4, fret: 5, duration: "16" }, { string: 4, fret: 7, duration: "16" }, { string: 4, fret: 9, duration: "16" },
                { string: 3, fret: 5, duration: "16" }, { string: 3, fret: 7, duration: "16" }, { string: 3, fret: 9, duration: "16" },
                { string: 2, fret: 5, duration: "16" }, { string: 2, fret: 7, duration: "16" }, { string: 2, fret: 8, duration: "16" },
                { string: 1, fret: 5, duration: "16" }, { string: 1, fret: 7, duration: "16" }, { string: 1, fret: 8, duration: "16" },
                { string: 2, fret: 8, duration: "16" }, { string: 2, fret: 7, duration: "16" }, { string: 2, fret: 5, duration: "16" },
                { string: 3, fret: 9, duration: "16" }, { string: 3, fret: 7, duration: "16" }, { string: 3, fret: 5, duration: "16" },
                { string: 4, fret: 9, duration: "16" }, { string: 4, fret: 7, duration: "16" }, { string: 4, fret: 5, duration: "16" },
                { string: 5, fret: 8, duration: "16" }, { string: 5, fret: 7, duration: "16" }, { string: 5, fret: 5, duration: "16" },
                { string: 6, fret: 8, duration: "16" }, { string: 6, fret: 7, duration: "16" }, { string: 6, fret: 5, duration: "16" },
              ],
            },
          ],
        },
        {
          id: "3-4",
          title: "Settimane 3-4 — Metodo a scatti per rompere il muro",
          exercises: [
            {
              id: "1.1",
              title: "Burst training — 3NPC La minore (metodo a scatti)",
              technique: "Alternate Picking",
              bpm: 100,
              bpmTarget: 130,
              tab: [
                "e|--5-7-8-5-7-8--|",
                "B|--5-7-8-5-7-8--|",
                "G|--5-7-9-5-7-9--|",
                "D|--5-7-9-5-7-9--|",
                "A|--5-7-8-5-7-8--|",
                "E|--5-7-8-5-7-8--|",
              ],
              tip: "Step 1: 100 BPM × 2 min (comfort). Step 2: 120 BPM × 30 sec (burst). Step 3: 100 BPM × 1 min (recovery — sembrerà lentissimo). Step 4: 122 BPM × 30 sec. Ripeti 4 cicli. Questo è il metodo più efficace documentato per superare un plateau di BPM.",
              notes: [
                { string: 6, fret: 5, duration: "16" }, { string: 6, fret: 7, duration: "16" }, { string: 6, fret: 8, duration: "16" },
                { string: 5, fret: 5, duration: "16" }, { string: 5, fret: 7, duration: "16" }, { string: 5, fret: 8, duration: "16" },
                { string: 4, fret: 5, duration: "16" }, { string: 4, fret: 7, duration: "16" }, { string: 4, fret: 9, duration: "16" },
                { string: 3, fret: 5, duration: "16" }, { string: 3, fret: 7, duration: "16" }, { string: 3, fret: 9, duration: "16" },
                { string: 2, fret: 5, duration: "16" }, { string: 2, fret: 7, duration: "16" }, { string: 2, fret: 8, duration: "16" },
                { string: 1, fret: 5, duration: "16" }, { string: 1, fret: 7, duration: "16" }, { string: 1, fret: 8, duration: "16" },
              ],
            },
            {
              id: "1.2",
              title: "Pattern 4-note — gruppi di 4 su tutta la tastiera",
              technique: "Alternate Picking",
              bpm: 100,
              bpmTarget: 125,
              tab: [
                "e|--5-7-8-10--7-8-10-12--8-10-12-13--12-10-8-7--|",
                "B|------------------------------------------------|",
                "G|------------------------------------------------|",
                "D|------------------------------------------------|",
                "A|------------------------------------------------|",
                "E|------------------------------------------------|",
              ],
              tip: "Gruppi di 4 note consecutive, poi torna indietro di uno. Crea un moto ondulatorio — il pattern tipico di Petrucci nei passaggi scalari veloci. Concentrati sulla parità dinamica: il primo di ogni gruppo tende a essere accentato involontariamente, ammorbidiscilo.",
              notes: [
                { string: 1, fret: 5, duration: "16" }, { string: 1, fret: 7, duration: "16" }, { string: 1, fret: 8, duration: "16" }, { string: 1, fret: 10, duration: "16" },
                { string: 1, fret: 7, duration: "16" }, { string: 1, fret: 8, duration: "16" }, { string: 1, fret: 10, duration: "16" }, { string: 1, fret: 12, duration: "16" },
                { string: 1, fret: 8, duration: "16" }, { string: 1, fret: 10, duration: "16" }, { string: 1, fret: 12, duration: "16" }, { string: 1, fret: 13, duration: "16" },
                { string: 1, fret: 12, duration: "16" }, { string: 1, fret: 10, duration: "16" }, { string: 1, fret: 8, duration: "16" }, { string: 1, fret: 7, duration: "16" },
              ],
            },
            {
              id: "1.3",
              title: "Scala in terze — picking alternato veloce",
              technique: "Alternate Picking",
              bpm: 95,
              bpmTarget: 118,
              tab: [
                "e|--5-8--7-10--8-12--10-13--12-15--|",
                "B|--5-8--7-10--8-12--10-13---------|",
                "G|---------------------------------|",
                "D|---------------------------------|",
                "A|---------------------------------|",
                "E|---------------------------------|",
              ],
              tip: "Terze su due corde: il picking salta una corda ad ogni nota. È il pattern più difficile per il pick slanting perché devi alternare DPS/UPS ad ogni singola nota. Inizia lentissimo (60 BPM) per costruire la mappa motoria, poi accelera. Non saltare questa fase lenta.",
              notes: [
                { string: 2, fret: 5, duration: "16" }, { string: 1, fret: 8, duration: "16" },
                { string: 2, fret: 7, duration: "16" }, { string: 1, fret: 10, duration: "16" },
                { string: 2, fret: 8, duration: "16" }, { string: 1, fret: 12, duration: "16" },
                { string: 2, fret: 10, duration: "16" }, { string: 1, fret: 13, duration: "16" },
                { string: 2, fret: 12, duration: "16" }, { string: 1, fret: 15, duration: "16" },
              ],
            },
            {
              id: "1.4",
              title: "Pattern 3NPC — posizioni diverse (non solo 5a)",
              technique: "Alternate Picking",
              bpm: 100,
              bpmTarget: 120,
              tab: [
                "e|--8-10-12--10-12-13--12-13-15--13-15-17--|",
                "B|--8-10-12--10-12-13--12-13-15--13-15-17--|",
                "G|--9-10-12--10-12-14--12-14-15--14-15-17--|",
                "D|--9-10-12--10-12-14--12-14-15--14-15-17--|",
                "A|--8-10-12--10-12-13--12-13-15--13-15-17--|",
                "E|--8-10-12--10-12-13--12-13-15--13-15-17--|",
              ],
              tip: "Scala di La minore in 4 posizioni consecutive (8a, 10a, 12a, 13a). Spostarsi tra le posizioni è fondamentale per Another Day che usa tutta la tastiera. Il punto critico è lo slide tra le posizioni: non perdere il tempo.",
              notes: [
                { string: 6, fret: 8, duration: "16" }, { string: 6, fret: 10, duration: "16" }, { string: 6, fret: 12, duration: "16" },
                { string: 5, fret: 8, duration: "16" }, { string: 5, fret: 10, duration: "16" }, { string: 5, fret: 12, duration: "16" },
                { string: 4, fret: 9, duration: "16" }, { string: 4, fret: 10, duration: "16" }, { string: 4, fret: 12, duration: "16" },
                { string: 3, fret: 9, duration: "16" }, { string: 3, fret: 10, duration: "16" }, { string: 3, fret: 12, duration: "16" },
                { string: 2, fret: 8, duration: "16" }, { string: 2, fret: 10, duration: "16" }, { string: 2, fret: 12, duration: "16" },
                { string: 1, fret: 8, duration: "16" }, { string: 1, fret: 10, duration: "16" }, { string: 1, fret: 12, duration: "16" },
              ],
            },
          ],
        },
      ],
    },
    {
      id: 2,
      title: "Mese 2 — Sestine e Sincronizzazione Avanzata",
      objective: "Introdurre le sestine (il ritmo esatto di Another Day). Portare il picking da 120 a 140 BPM sedicesimi. Lavorare sulla sincronizzazione mani ad alta velocità.",
      weeks: [
        {
          id: "5-6",
          title: "Settimane 5-6 — Introduzione alle sestine",
          exercises: [
            {
              id: "2.1",
              title: "Sestine — 3NPC La minore (il ritmo di Another Day)",
              technique: "Alternate Picking",
              bpm: 80,
              bpmTarget: 110,
              tab: [
                "e|--5-7-8-5-7-8--|  (sestine = 6 note per beat)",
                "B|--5-7-8-5-7-8--|",
                "G|--5-7-9-5-7-9--|",
                "D|--5-7-9-5-7-9--|",
                "A|--5-7-8-5-7-8--|",
                "E|--5-7-8-5-7-8--|",
              ],
              tip: "SESTINE = 6 note per battito. A 80 BPM il rate di note è identico a 120 BPM in sedicesimi. È il ritmo esatto della parte veloce di Another Day. Conta ad alta voce: 1-2-3-4-5-6 per ogni beat. Il ciclo di 6 note su 3NPC crea un'asimmetria interessante: il DOWN stroke non cade sempre sulla stessa nota.",
              notes: [
                { string: 6, fret: 5, duration: "16" }, { string: 6, fret: 7, duration: "16" }, { string: 6, fret: 8, duration: "16" },
                { string: 5, fret: 5, duration: "16" }, { string: 5, fret: 7, duration: "16" }, { string: 5, fret: 8, duration: "16" },
                { string: 4, fret: 5, duration: "16" }, { string: 4, fret: 7, duration: "16" }, { string: 4, fret: 9, duration: "16" },
                { string: 3, fret: 5, duration: "16" }, { string: 3, fret: 7, duration: "16" }, { string: 3, fret: 9, duration: "16" },
              ],
            },
            {
              id: "2.2",
              title: "Sestine — pattern inverso (discendente) poi combinato",
              technique: "Alternate Picking",
              bpm: 80,
              bpmTarget: 110,
              tab: [
                "e|--8-7-5-8-7-5--8-7-5-8-7-5--|",
                "B|--8-7-5-8-7-5--8-7-5-8-7-5--|",
                "G|--9-7-5-9-7-5--9-7-5-9-7-5--|",
                "D|--9-7-5-9-7-5--9-7-5-9-7-5--|",
                "A|--8-7-5-8-7-5--8-7-5-8-7-5--|",
                "E|--8-7-5-8-7-5--8-7-5-8-7-5--|",
              ],
              tip: "Stesso esercizio ma discendente. Poi combina: 2 battute su, 2 battute giù senza fermarti. L'inversione di direzione è sempre il punto critico — non rallentare lì.",
              notes: [
                { string: 1, fret: 8, duration: "16" }, { string: 1, fret: 7, duration: "16" }, { string: 1, fret: 5, duration: "16" },
                { string: 2, fret: 8, duration: "16" }, { string: 2, fret: 7, duration: "16" }, { string: 2, fret: 5, duration: "16" },
                { string: 3, fret: 9, duration: "16" }, { string: 3, fret: 7, duration: "16" }, { string: 3, fret: 5, duration: "16" },
                { string: 4, fret: 9, duration: "16" }, { string: 4, fret: 7, duration: "16" }, { string: 4, fret: 5, duration: "16" },
              ],
            },
            {
              id: "2.3",
              title: "Sincronizzazione — test mani a 120 BPM sedicesimi",
              technique: "Sincronizzazione",
              bpm: 100,
              bpmTarget: 125,
              tab: [
                "e|--5-7-8-10-8-7--5-7-8-10-8-7--|",
                "B|-------------------------------|",
                "G|-------------------------------|",
                "D|-------------------------------|",
                "A|-------------------------------|",
                "E|-------------------------------|",
              ],
              tip: "6 note su una sola corda: testa pura sincronizzazione. Ogni nota deve avere IDENTICO volume. La nota 3 (8) e la nota 6 (7) tendono ad essere più deboli perché cadono su UP strokes. Se le senti più flebili: rallenta e rinforza specificamente quelle. Registra e ascolta critico.",
              notes: [
                { string: 1, fret: 5, duration: "16" }, { string: 1, fret: 7, duration: "16" }, { string: 1, fret: 8, duration: "16" },
                { string: 1, fret: 10, duration: "16" }, { string: 1, fret: 8, duration: "16" }, { string: 1, fret: 7, duration: "16" },
                { string: 1, fret: 5, duration: "16" }, { string: 1, fret: 7, duration: "16" }, { string: 1, fret: 8, duration: "16" },
                { string: 1, fret: 10, duration: "16" }, { string: 1, fret: 8, duration: "16" }, { string: 1, fret: 7, duration: "16" },
              ],
            },
          ],
        },
        {
          id: "7-8",
          title: "Settimane 7-8 — Legato veloce + combinazioni picking/legato",
          exercises: [
            {
              id: "2.4",
              title: "Legato veloce — 3NPC puro (mano destra quasi ferma)",
              technique: "Legato",
              bpm: 110,
              bpmTarget: 140,
              tab: [
                "e|--5h7h8--8p7p5--5h7h8--8p7p5--|",
                "B|--5h7h8--8p7p5--5h7h8--8p7p5--|",
                "G|--5h7h9--9p7p5--5h7h9--9p7p5--|",
                "D|--5h7h9--9p7p5--5h7h9--9p7p5--|",
                "A|--5h7h8--8p7p5--5h7h8--8p7p5--|",
                "E|--5h7h8--8p7p5--5h7h8--8p7p5--|",
              ],
              tip: "La destra pica SOLO la prima nota di ogni corda. Il legato può andare molto più veloce del picking perché elimina la resistenza del plettro. A 140 BPM il legato deve suonare uniforme: pull-off troppo forti = note schioccanti. Hammer-on troppo deboli = note soffocate. Obiettivo: indistinguibile da picking.",
              notes: [
                { string: 6, fret: 5, duration: "16" }, { string: 6, fret: 7, duration: "16", technique: "h" }, { string: 6, fret: 8, duration: "16", technique: "h" },
                { string: 6, fret: 8, duration: "16", technique: "p" }, { string: 6, fret: 7, duration: "16", technique: "p" }, { string: 6, fret: 5, duration: "16" },
                { string: 5, fret: 5, duration: "16" }, { string: 5, fret: 7, duration: "16", technique: "h" }, { string: 5, fret: 8, duration: "16", technique: "h" },
                { string: 5, fret: 8, duration: "16", technique: "p" }, { string: 5, fret: 7, duration: "16", technique: "p" }, { string: 5, fret: 5, duration: "16" },
              ],
            },
            {
              id: "2.5",
              title: "Combo picking + legato — pattern Petrucci tipico",
              technique: "Combinata",
              bpm: 95,
              bpmTarget: 120,
              tab: [
                "e|--5-7-8h10h12--12p10p8-7-5--|",
                "B|----------------------------|",
                "G|----------------------------|",
                "D|----------------------------|",
                "A|----------------------------|",
                "E|----------------------------|",
              ],
              tip: "Le prime 2 note con picking alternato, poi hammer-on fino in cima, poi pull-off fino in fondo, poi picking alternato gli ultimi 2. Questo è il pattern ibrido tipico di Petrucci: usa il legato per guadagnare velocità nelle note centrali senza perdere attacco sulle note di testa.",
              notes: [
                { string: 1, fret: 5, duration: "16" }, { string: 1, fret: 7, duration: "16" },
                { string: 1, fret: 8, duration: "16", technique: "h" }, { string: 1, fret: 10, duration: "16", technique: "h" }, { string: 1, fret: 12, duration: "16", technique: "h" },
                { string: 1, fret: 10, duration: "16", technique: "p" }, { string: 1, fret: 8, duration: "16", technique: "p" },
                { string: 1, fret: 7, duration: "16" }, { string: 1, fret: 5, duration: "16" },
              ],
            },
            {
              id: "2.6",
              title: "String skipping veloce — intervalli di sesta",
              technique: "String Skipping",
              bpm: 95,
              bpmTarget: 115,
              tab: [
                "e|--5-8--7-10--8-12--10-13--12-15--|",
                "G|--7-10--9-12--10-14--12-15--14-17-|",
                "B|-----------------------------------|",
                "D|-----------------------------------|",
                "A|-----------------------------------|",
                "E|-----------------------------------|",
              ],
              tip: "Seste su corde e e G (saltando B). Il plettro vola sulla corda B — con il tempo questo diventa automatico. A velocità alta il segreto è tenere il polso stabile: non oscillare su e giù, è solo un movimento di ampiezza maggiore del plettro.",
              notes: [
                { string: 1, fret: 5, duration: "16" }, { string: 3, fret: 7, duration: "16" },
                { string: 1, fret: 7, duration: "16" }, { string: 3, fret: 9, duration: "16" },
                { string: 1, fret: 8, duration: "16" }, { string: 3, fret: 10, duration: "16" },
                { string: 1, fret: 10, duration: "16" }, { string: 3, fret: 12, duration: "16" },
                { string: 1, fret: 12, duration: "16" }, { string: 3, fret: 14, duration: "16" },
              ],
            },
          ],
        },
      ],
    },
    {
      id: 3,
      title: "Mese 3 — Target 140 BPM e Pattern di Another Day",
      objective: "Portare picking a 140 BPM sedicesimi. Introdurre i pattern specifici dell'assolo. Sweep picking su 5 corde. Lavorare sull'esatta frase veloce di Another Day.",
      weeks: [
        {
          id: "9-10",
          title: "Settimane 9-10 — Burst estremo e pattern specifici",
          exercises: [
            {
              id: "3.1",
              title: "Burst estremo — 3NPC a 140 BPM (20 secondi)",
              technique: "Alternate Picking",
              bpm: 120,
              bpmTarget: 145,
              tab: [
                "e|--5-7-8--5-7-8--|",
                "B|--5-7-8--5-7-8--|",
                "G|--5-7-9--5-7-9--|",
                "D|--5-7-9--5-7-9--|",
                "A|--5-7-8--5-7-8--|",
                "E|--5-7-8--5-7-8--|",
              ],
              tip: "Sessione burst estremo: 110 BPM × 90 sec → 130 BPM × 30 sec → 110 BPM × 60 sec → 135 BPM × 20 sec → 110 BPM × 60 sec → 140 BPM × 10 sec. I 10 secondi a 140 non devono essere perfetti — devono solo essere controllati. La perfezione arriverà nelle settimane successive.",
              notes: [
                { string: 6, fret: 5, duration: "16" }, { string: 6, fret: 7, duration: "16" }, { string: 6, fret: 8, duration: "16" },
                { string: 5, fret: 5, duration: "16" }, { string: 5, fret: 7, duration: "16" }, { string: 5, fret: 8, duration: "16" },
                { string: 4, fret: 5, duration: "16" }, { string: 4, fret: 7, duration: "16" }, { string: 4, fret: 9, duration: "16" },
                { string: 3, fret: 5, duration: "16" }, { string: 3, fret: 7, duration: "16" }, { string: 3, fret: 9, duration: "16" },
                { string: 2, fret: 5, duration: "16" }, { string: 2, fret: 7, duration: "16" }, { string: 2, fret: 8, duration: "16" },
                { string: 1, fret: 5, duration: "16" }, { string: 1, fret: 7, duration: "16" }, { string: 1, fret: 8, duration: "16" },
              ],
            },
            {
              id: "3.2",
              title: "Pattern Another Day — frase veloce in 12a posizione",
              technique: "Alternate Picking",
              bpm: 100,
              bpmTarget: 135,
              tab: [
                "e|--12-14-15-12-14-15--|",
                "B|--12-14-15-12-14-15--|",
                "G|--12-14-16-12-14-16--|",
                "D|--12-14-16-12-14-16--|",
                "A|--12-14-15-12-14-15--|",
                "E|--12-14-15-12-14-15--|",
              ],
              tip: "Questa è la posizione (12a) dove si svolge la parte veloce di Another Day. La fingering è leggermente diversa dalla 5a posizione: dito 1 sul 12, dito 3 sul 14, dito 4 sul 15 (o 16). L'estensione tra il 3 e il 4 dito è più impegnativa — dedica le prime sessioni solo alla mano sinistra senza picking.",
              notes: [
                { string: 6, fret: 12, duration: "16" }, { string: 6, fret: 14, duration: "16" }, { string: 6, fret: 15, duration: "16" },
                { string: 5, fret: 12, duration: "16" }, { string: 5, fret: 14, duration: "16" }, { string: 5, fret: 15, duration: "16" },
                { string: 4, fret: 12, duration: "16" }, { string: 4, fret: 14, duration: "16" }, { string: 4, fret: 16, duration: "16" },
                { string: 3, fret: 12, duration: "16" }, { string: 3, fret: 14, duration: "16" }, { string: 3, fret: 16, duration: "16" },
                { string: 2, fret: 12, duration: "16" }, { string: 2, fret: 14, duration: "16" }, { string: 2, fret: 15, duration: "16" },
                { string: 1, fret: 12, duration: "16" }, { string: 1, fret: 14, duration: "16" }, { string: 1, fret: 15, duration: "16" },
              ],
            },
            {
              id: "3.3",
              title: "Sweep picking 5 corde — arpeggio Am/Am7",
              technique: "Sweep Picking",
              bpm: 70,
              bpmTarget: 100,
              tab: [
                "e|--5h8----------8p5--|",
                "B|-----10------10-----|",
                "G|-------9--9--------|",
                "D|--------7----------|",
                "A|-------------------|",
                "E|-------------------|",
              ],
              tip: "Sweep su 5 corde: down sweep E→e poi up sweep e→E. La mano sinistra deve rilasciare ogni nota immediatamente dopo averla suonata — se senti le note sovrapporsi rallenta di 20 BPM. Il punto critico è la nota di vertice (8 sul e): lì il movimento del plettro cambia direzione senza fermarsi.",
              notes: [
                { string: 1, fret: 5, duration: "8" }, { string: 1, fret: 8, duration: "8", technique: "h" },
                { string: 2, fret: 10, duration: "8" }, { string: 3, fret: 9, duration: "8" }, { string: 4, fret: 7, duration: "8" },
                { string: 3, fret: 9, duration: "8" }, { string: 2, fret: 10, duration: "8" },
                { string: 1, fret: 8, duration: "8", technique: "p" }, { string: 1, fret: 5, duration: "8" },
              ],
            },
            {
              id: "3.4",
              title: "Sequenza discendente veloce — lick stile Another Day",
              technique: "Combinata",
              bpm: 95,
              bpmTarget: 125,
              tab: [
                "e|--17-15-14-12-15-14-12-10-14-12-10-8-12-10-8-5--|",
                "B|--------------------------------------------------|",
                "G|--------------------------------------------------|",
                "D|--------------------------------------------------|",
                "A|--------------------------------------------------|",
                "E|--------------------------------------------------|",
              ],
              tip: "Scala discendente in 3NPC su una sola corda (corda e) dalla 17a alla 5a posizione. Isola la difficoltà: solo picking, nessun cambio di corda. Obiettivo = fluire senza micro-pause tra i gruppi di 3. Il cervello tende ad inserire una pausa inconscia ogni 3 note — eliminala.",
              notes: [
                { string: 1, fret: 17, duration: "16" }, { string: 1, fret: 15, duration: "16" }, { string: 1, fret: 14, duration: "16" },
                { string: 1, fret: 12, duration: "16" }, { string: 1, fret: 15, duration: "16" }, { string: 1, fret: 14, duration: "16" },
                { string: 1, fret: 12, duration: "16" }, { string: 1, fret: 10, duration: "16" }, { string: 1, fret: 14, duration: "16" },
                { string: 1, fret: 12, duration: "16" }, { string: 1, fret: 10, duration: "16" }, { string: 1, fret: 8, duration: "16" },
                { string: 1, fret: 12, duration: "16" }, { string: 1, fret: 10, duration: "16" }, { string: 1, fret: 8, duration: "16" },
                { string: 1, fret: 5, duration: "q" },
              ],
            },
          ],
        },
        {
          id: "11-12",
          title: "Settimane 11-12 — Frase completa e contesto musicale",
          exercises: [
            {
              id: "3.5",
              title: "Another Day — frase veloce completa (semplificata)",
              technique: "Combinata",
              bpm: 85,
              bpmTarget: 120,
              tab: [
                "e|--12-14-15-17-15-14--12-14-15-17-15-14--|",
                "B|--12-14-15-17-15-14--12-14-15-17-15-14--|",
                "G|--12-14-16-17-16-14--12-14-16-17-16-14--|",
                "D|-----------------------------------------|",
                "A|-----------------------------------------|",
                "E|-----------------------------------------|",
              ],
              tip: "La frase veloce di Another Day in versione semplificata: ascendi su 3 corde poi scendi sulle stesse. Quando questo gira pulito a 120 BPM puoi affrontare la versione originale a tempo pieno (che è circa 138-140 BPM nei sedicesimi). Non affrettare questa fase.",
              notes: [
                { string: 4, fret: 12, duration: "16" }, { string: 4, fret: 14, duration: "16" }, { string: 4, fret: 16, duration: "16" },
                { string: 3, fret: 12, duration: "16" }, { string: 3, fret: 14, duration: "16" }, { string: 3, fret: 16, duration: "16" },
                { string: 2, fret: 12, duration: "16" }, { string: 2, fret: 14, duration: "16" }, { string: 2, fret: 15, duration: "16" },
                { string: 1, fret: 12, duration: "16" }, { string: 1, fret: 14, duration: "16" }, { string: 1, fret: 15, duration: "16" },
                { string: 2, fret: 15, duration: "16" }, { string: 2, fret: 14, duration: "16" }, { string: 2, fret: 12, duration: "16" },
                { string: 3, fret: 16, duration: "16" }, { string: 3, fret: 14, duration: "16" }, { string: 3, fret: 12, duration: "16" },
              ],
            },
            {
              id: "3.6",
              title: "Legato + picking ibrido — velocità massima",
              technique: "Combinata",
              bpm: 100,
              bpmTarget: 130,
              tab: [
                "e|--12h14h15--15-14--12h14h15--15-14-12--|",
                "B|-------------------------------------15-|",
                "G|----------------------------------------|",
                "D|----------------------------------------|",
                "A|----------------------------------------|",
                "E|----------------------------------------|",
              ],
              tip: "Legato sui primi 3 (hammer-on) poi picking alternato sugli ultimi 2. Il cambio legato→picking non deve creare una pausa o un accento involontario. Esercitati a tenere il volume uniforme attraverso il cambio di tecnica — questo è il vero difficile.",
              notes: [
                { string: 1, fret: 12, duration: "16" }, { string: 1, fret: 14, duration: "16", technique: "h" }, { string: 1, fret: 15, duration: "16", technique: "h" },
                { string: 1, fret: 15, duration: "16" }, { string: 1, fret: 14, duration: "16" },
                { string: 1, fret: 12, duration: "16" }, { string: 1, fret: 14, duration: "16", technique: "h" }, { string: 1, fret: 15, duration: "16", technique: "h" },
                { string: 1, fret: 15, duration: "16" }, { string: 1, fret: 14, duration: "16" }, { string: 1, fret: 12, duration: "16" },
                { string: 2, fret: 15, duration: "q" },
              ],
            },
          ],
        },
      ],
    },
    {
      id: 4,
      title: "Mese 4 — Another Day a Tempo e Musicalità Avanzata",
      objective: "Portare il picking a 150 BPM. Suonare la frase veloce di Another Day a tempo reale. Costruire frasi complesse che combinano tutte le tecniche con espressività vera.",
      weeks: [
        {
          id: "13-14",
          title: "Settimane 13-14 — Velocità massima e Another Day originale",
          exercises: [
            {
              id: "4.1",
              title: "3NPC a 150 BPM — il target finale",
              technique: "Alternate Picking",
              bpm: 130,
              bpmTarget: 150,
              tab: [
                "e|--5-7-8-5-7-8--|",
                "B|--5-7-8-5-7-8--|",
                "G|--5-7-9-5-7-9--|",
                "D|--5-7-9-5-7-9--|",
                "A|--5-7-8-5-7-8--|",
                "E|--5-7-8-5-7-8--|",
              ],
              tip: "150 BPM sedicesimi = sestine di trentaduesimi a 100 BPM. Se ci sei arrivato hai sbloccato la parte veloce di Another Day. Sessione: 130 BPM × 2 min, 140 BPM × 1 min, 145 BPM × 30 sec, 150 BPM × 15 sec. Non forzare mai 150 BPM per più di 15 secondi nelle prime settimane.",
              notes: [
                { string: 6, fret: 5, duration: "16" }, { string: 6, fret: 7, duration: "16" }, { string: 6, fret: 8, duration: "16" },
                { string: 5, fret: 5, duration: "16" }, { string: 5, fret: 7, duration: "16" }, { string: 5, fret: 8, duration: "16" },
                { string: 4, fret: 5, duration: "16" }, { string: 4, fret: 7, duration: "16" }, { string: 4, fret: 9, duration: "16" },
                { string: 3, fret: 5, duration: "16" }, { string: 3, fret: 7, duration: "16" }, { string: 3, fret: 9, duration: "16" },
                { string: 2, fret: 5, duration: "16" }, { string: 2, fret: 7, duration: "16" }, { string: 2, fret: 8, duration: "16" },
                { string: 1, fret: 5, duration: "16" }, { string: 1, fret: 7, duration: "16" }, { string: 1, fret: 8, duration: "16" },
              ],
            },
            {
              id: "4.2",
              title: "Another Day — frase veloce a tempo reale",
              technique: "Alternate Picking",
              bpm: 100,
              bpmTarget: 138,
              tab: [
                "e|--12-14-15-17-19-17--15-14-12-15-14-12--|",
                "B|--12-14-15-17-19-17--15-14-12-15-14-12--|",
                "G|--12-14-16-17-19-17--16-14-12-16-14-12--|",
                "D|-----------------------------------------|",
                "A|-----------------------------------------|",
                "E|-----------------------------------------|",
              ],
              tip: "La frase veloce di Another Day a BPM reale (138 sedicesimi). Impara prima le singole frasi isolate, poi collegale. Il punto più difficile è il cambio di corda da G a B: lì il ritmo tende a sbriciolarsi. Isola quel cambio specifico e lavoraci 5 minuti ogni sessione.",
              notes: [
                { string: 4, fret: 12, duration: "16" }, { string: 4, fret: 14, duration: "16" }, { string: 4, fret: 16, duration: "16" },
                { string: 3, fret: 12, duration: "16" }, { string: 3, fret: 14, duration: "16" }, { string: 3, fret: 16, duration: "16" },
                { string: 2, fret: 12, duration: "16" }, { string: 2, fret: 14, duration: "16" }, { string: 2, fret: 15, duration: "16" },
                { string: 1, fret: 12, duration: "16" }, { string: 1, fret: 14, duration: "16" }, { string: 1, fret: 15, duration: "16" },
                { string: 1, fret: 17, duration: "16" }, { string: 1, fret: 15, duration: "16" }, { string: 1, fret: 14, duration: "16" },
                { string: 1, fret: 12, duration: "16" }, { string: 2, fret: 15, duration: "16" }, { string: 2, fret: 14, duration: "16" },
              ],
            },
            {
              id: "4.3",
              title: "Frase espressiva lunga — legato + picking + sweep + bend",
              technique: "Combinata",
              bpm: 85,
              bpmTarget: 110,
              tab: [
                "e|--12h15h17--17p15p12--12-15-17-15-12--17b19~--|",
                "B|----------------------------------15------------|",
                "G|------------------------------------------14---|",
                "D|------------------------------------------------|",
                "A|------------------------------------------------|",
                "E|------------------------------------------------|",
              ],
              tip: "Frase completa: legato ascendente (3 note) → picking discendente → legato ascendente → picking → bend finale con vibrato lungo. Suonala senza metronomo prima, poi con. Il bend finale deve tenere almeno 2 secondi di vibrato — non fermarti dopo il bend.",
              notes: [
                { string: 1, fret: 12, duration: "16" }, { string: 1, fret: 15, duration: "16", technique: "h" }, { string: 1, fret: 17, duration: "16", technique: "h" },
                { string: 1, fret: 15, duration: "16", technique: "p" }, { string: 1, fret: 12, duration: "16", technique: "p" },
                { string: 1, fret: 12, duration: "16" }, { string: 1, fret: 15, duration: "16" }, { string: 1, fret: 17, duration: "16" },
                { string: 1, fret: 15, duration: "16" }, { string: 1, fret: 12, duration: "16" },
                { string: 2, fret: 15, duration: "8" }, { string: 3, fret: 14, duration: "8" },
                { string: 1, fret: 17, duration: "8", technique: "b" }, { string: 1, fret: 19, duration: "h", technique: "~" },
              ],
            },
          ],
        },
        {
          id: "15-16",
          title: "Settimane 15-16 — Musicalità e assolo completo",
          exercises: [
            {
              id: "4.4",
              title: "Lick fusion veloce — string skipping + legato + bend",
              technique: "Combinata",
              bpm: 90,
              bpmTarget: 118,
              tab: [
                "e|--12-15--12h15h17--17p15p12--12b14~--|",
                "B|--15-----------------------------15---|",
                "G|--------------------------------------|",
                "D|--------------------------------------|",
                "A|--------------------------------------|",
                "E|--------------------------------------|",
              ],
              tip: "Skip e→B poi ritorna sulla e con legato. Il cambio di corda saltata al ritorno (B→e) è il punto critico. Stile Petrucci/Guthrie Govan: inizia su una nota bassa, sale veloce con legato, risolve sul bend. La frase deve 'volare' — se suona meccanica rallenta.",
              notes: [
                { string: 1, fret: 12, duration: "16" }, { string: 2, fret: 15, duration: "16" },
                { string: 1, fret: 12, duration: "16" }, { string: 1, fret: 15, duration: "16", technique: "h" }, { string: 1, fret: 17, duration: "16", technique: "h" },
                { string: 1, fret: 15, duration: "16", technique: "p" }, { string: 1, fret: 12, duration: "16", technique: "p" },
                { string: 1, fret: 12, duration: "8", technique: "b" }, { string: 1, fret: 14, duration: "q", technique: "~" },
                { string: 2, fret: 15, duration: "q" },
              ],
            },
            {
              id: "4.5",
              title: "Assolo libero su BT-5 — applica tutto",
              technique: "Improvvisazione",
              bpm: 85,
              bpmTarget: 138,
              tab: [
                "e|--17~--15p12--14b15~--12-15-17-15-12--|",
                "B|----------------------------------15---|",
                "G|------------------------------------14-|",
                "D|---------------------------------------|",
                "A|---------------------------------------|",
                "E|---------------------------------------|",
              ],
              tip: "Suona su BT-5 (Am-Fmaj7-Dm7-E7 a 85 BPM). Ogni battuta: 1 frase lenta espressiva + 1 frase veloce 3NPC + silenzio. La velocità fine a sé stessa non vale nulla senza musicalità. Registra ogni sessione e ascoltati il giorno dopo — la prospettiva cambia sempre.",
              notes: [
                { string: 1, fret: 17, duration: "h", technique: "~" },
                { string: 1, fret: 15, duration: "16", technique: "p" }, { string: 1, fret: 12, duration: "16" },
                { string: 1, fret: 14, duration: "16", technique: "b" }, { string: 1, fret: 15, duration: "q", technique: "~" },
                { string: 1, fret: 12, duration: "16" }, { string: 1, fret: 15, duration: "16" }, { string: 1, fret: 17, duration: "16" },
                { string: 1, fret: 15, duration: "16" }, { string: 1, fret: 12, duration: "16" },
                { string: 2, fret: 15, duration: "8" }, { string: 3, fret: 14, duration: "q" },
              ],
            },
          ],
        },
      ],
    },
  ],

  melodicExercises: [
    {
      id: "M1.1",
      title: "Sequenza a Terze veloci — tutta la tastiera",
      chapter: "Cap. 1 — Sequenze su Scala",
      sound: "Classico, orchestrale. Il pattern che sale e scende con eleganza.",
      bpm: 95,
      tab: [
        "e|--5-8--7-10--8-12--10-13--12-15--13-17--|",
        "B|--5-8--7-10--8-12--10-13--12-15---------|",
        "G|-----------------------------------------|",
        "D|-----------------------------------------|",
        "A|-----------------------------------------|",
        "E|-----------------------------------------|",
      ],
      tip: "Terze ascendenti fino al 15° tasto poi inversione. Il picking su corde non adiacenti richiede UPS su ogni nota alta e DPS su ogni nota bassa — il polso oscilla ritmicamente. A 95 BPM questo è già un esercizio impegnativo.",
      notes: [
        { string: 2, fret: 5, duration: "16" }, { string: 1, fret: 8, duration: "16" },
        { string: 2, fret: 7, duration: "16" }, { string: 1, fret: 10, duration: "16" },
        { string: 2, fret: 8, duration: "16" }, { string: 1, fret: 12, duration: "16" },
        { string: 2, fret: 10, duration: "16" }, { string: 1, fret: 13, duration: "16" },
        { string: 2, fret: 12, duration: "16" }, { string: 1, fret: 15, duration: "16" },
        { string: 2, fret: 13, duration: "16" }, { string: 1, fret: 17, duration: "16" },
      ],
    },
    {
      id: "M1.2",
      title: "Gruppi di 4 — progressione su tutta la tastiera",
      chapter: "Cap. 1 — Sequenze su Scala",
      sound: "Fluido, moderno. Il pattern scalare tipico di Petrucci.",
      bpm: 100,
      tab: [
        "e|--5-7-8-10--7-8-10-12--8-10-12-13--10-12-13-15--12-13-15-17--|",
        "B|--------------------------------------------------------------|",
        "G|--------------------------------------------------------------|",
        "D|--------------------------------------------------------------|",
        "A|--------------------------------------------------------------|",
        "E|--------------------------------------------------------------|",
      ],
      tip: "4 note poi torna di uno e ripeti. Suona senza fermarsi dall'inizio alla fine della corda e poi torna indietro. Non mettere accenti involontari sul primo di ogni gruppo: la fluidità è tutto.",
      notes: [
        { string: 1, fret: 5, duration: "16" }, { string: 1, fret: 7, duration: "16" }, { string: 1, fret: 8, duration: "16" }, { string: 1, fret: 10, duration: "16" },
        { string: 1, fret: 7, duration: "16" }, { string: 1, fret: 8, duration: "16" }, { string: 1, fret: 10, duration: "16" }, { string: 1, fret: 12, duration: "16" },
        { string: 1, fret: 8, duration: "16" }, { string: 1, fret: 10, duration: "16" }, { string: 1, fret: 12, duration: "16" }, { string: 1, fret: 13, duration: "16" },
        { string: 1, fret: 10, duration: "16" }, { string: 1, fret: 12, duration: "16" }, { string: 1, fret: 13, duration: "16" }, { string: 1, fret: 15, duration: "16" },
      ],
    },
    {
      id: "M2.1",
      title: "Frase in Re Dorico — versione estesa veloce",
      chapter: "Cap. 2 — Frasi Modali Avanzate",
      sound: "Scuro, metallico, jazz. Petrucci usa il dorico nei momenti più intensi.",
      bpm: 90,
      tab: [
        "e|--10h12h14--14-12--10h12h14--14-12-10--12b14~--|",
        "B|--------------------------------------------13--|",
        "G|------------------------------------------------|",
        "D|------------------------------------------------|",
        "A|------------------------------------------------|",
        "E|------------------------------------------------|",
      ],
      tip: "Frase dorica estesa: legato veloce in salita, picking in discesa, bend di risoluzione. La nota B naturale (14° tasto corda e) è il colore esotico del modo — accentala leggermente prima del bend finale. Suona sopra Dm7.",
      notes: [
        { string: 1, fret: 10, duration: "16" }, { string: 1, fret: 12, duration: "16", technique: "h" }, { string: 1, fret: 14, duration: "16", technique: "h" },
        { string: 1, fret: 14, duration: "16" }, { string: 1, fret: 12, duration: "16" },
        { string: 1, fret: 10, duration: "16" }, { string: 1, fret: 12, duration: "16", technique: "h" }, { string: 1, fret: 14, duration: "16", technique: "h" },
        { string: 1, fret: 14, duration: "16" }, { string: 1, fret: 12, duration: "16" }, { string: 1, fret: 10, duration: "16" },
        { string: 1, fret: 12, duration: "8", technique: "b" }, { string: 2, fret: 13, duration: "q", technique: "~" },
      ],
    },
    {
      id: "M2.2",
      title: "Frase in Mi Frigio — pattern aggressivo multi-corda",
      chapter: "Cap. 2 — Frasi Modali Avanzate",
      sound: "Oscuro, minaccioso, flamenco-metal.",
      bpm: 95,
      tab: [
        "e|--12-13-12-10--12-10-9-7--9-7-5-4--|",
        "B|-----------------------------------|",
        "G|-----------------------------------|",
        "D|-----------------------------------|",
        "A|-----------------------------------|",
        "E|-----------------------------------|",
      ],
      tip: "Frase frigia discendente su tutta la corda. La caratteristica è l'intervallo di semitono (12-13) all'inizio: suonalo netto e pulito, non lasciarlo scivolare come un bend. Poi la discesa deve essere fluida e veloce. È il tipo di frase che spaventa per la lunghezza — imparala a metà BPM prima.",
      notes: [
        { string: 1, fret: 12, duration: "16" }, { string: 1, fret: 13, duration: "16" }, { string: 1, fret: 12, duration: "16" }, { string: 1, fret: 10, duration: "16" },
        { string: 1, fret: 12, duration: "16" }, { string: 1, fret: 10, duration: "16" }, { string: 1, fret: 9, duration: "16" }, { string: 1, fret: 7, duration: "16" },
        { string: 1, fret: 9, duration: "16" }, { string: 1, fret: 7, duration: "16" }, { string: 1, fret: 5, duration: "16" }, { string: 1, fret: 4, duration: "q" },
      ],
    },
    {
      id: "M2.3",
      title: "Frase in Fa Lidio — legato esteso + bend",
      chapter: "Cap. 2 — Frasi Modali Avanzate",
      sound: "Luminoso, sognante, Satriani in modalità epica.",
      bpm: 85,
      tab: [
        "e|--13h15h17h18--18p17p15p13--15b17~--13h15h18~--|",
        "B|------------------------------------------------|",
        "G|------------------------------------------------|",
        "D|------------------------------------------------|",
        "A|------------------------------------------------|",
        "E|------------------------------------------------|",
      ],
      tip: "Legato ascendente su 4 note (raro — richiede 4 dita indipendenti), pull-off discendente, bend, poi seconda frase con legato + vibrato lungo. Il 18° tasto (B#/C) è il #4 lidio: accentalo. Suona su Fmaj7 o Cmaj7.",
      notes: [
        { string: 1, fret: 13, duration: "16" }, { string: 1, fret: 15, duration: "16", technique: "h" },
        { string: 1, fret: 17, duration: "16", technique: "h" }, { string: 1, fret: 18, duration: "16", technique: "h" },
        { string: 1, fret: 17, duration: "16", technique: "p" }, { string: 1, fret: 15, duration: "16", technique: "p" }, { string: 1, fret: 13, duration: "16", technique: "p" },
        { string: 1, fret: 15, duration: "8", technique: "b" }, { string: 1, fret: 17, duration: "q", technique: "~" },
        { string: 1, fret: 13, duration: "16" }, { string: 1, fret: 15, duration: "16", technique: "h" }, { string: 1, fret: 18, duration: "h", technique: "~" },
      ],
    },
    {
      id: "M3.1",
      title: "Frase Vocale Lunga — stile Another Day parte lenta",
      chapter: "Cap. 3 — Stile Petrucci Avanzato",
      sound: "Malinconico, cinematico. La parte che già sai fare bene — portala al livello successivo.",
      bpm: 0,
      tab: [
        "e|--15~~~~~--15p12--14b15~--12--15-17-15-12--17b19~~~--|",
        "B|--------------------------------------------------15--|",
        "G|-----------------------------------------------------|",
        "D|-----------------------------------------------------|",
        "A|-----------------------------------------------------|",
        "E|-----------------------------------------------------|",
      ],
      tip: "Frase completa: nota lunga con vibrato → discesa legato → risoluzione bend → pausa → frase veloce → bend finale lungo. La transizione lento→veloce dentro la stessa frase è il marchio di Petrucci. Non aumentare volume sulla parte veloce: mantieni lo stesso livello dinamico.",
      notes: [
        { string: 1, fret: 15, duration: "h", technique: "~" },
        { string: 1, fret: 15, duration: "16", technique: "p" }, { string: 1, fret: 12, duration: "16" },
        { string: 1, fret: 14, duration: "16", technique: "b" }, { string: 1, fret: 15, duration: "q", technique: "~" },
        { string: 1, fret: 12, duration: "16" }, { string: 1, fret: 15, duration: "16" }, { string: 1, fret: 17, duration: "16" },
        { string: 1, fret: 15, duration: "16" }, { string: 1, fret: 12, duration: "16" },
        { string: 1, fret: 17, duration: "8", technique: "b" }, { string: 1, fret: 19, duration: "h", technique: "~" },
        { string: 2, fret: 15, duration: "q" },
      ],
    },
    {
      id: "M3.2",
      title: "Crescendo da lento a sestine — dinamica estrema",
      chapter: "Cap. 3 — Stile Petrucci Avanzato",
      sound: "Cinematico, epico. La struttura del grande assolo.",
      bpm: 85,
      tab: [
        "e|--12~--15~--17~--19~~~~--17-15-14-12-15-14-12-10--|",
        "B|----------------------------------------------------|",
        "G|----------------------------------------------------|",
        "D|----------------------------------------------------|",
        "A|----------------------------------------------------|",
        "E|----------------------------------------------------|",
      ],
      tip: "4 note singole con vibrato crescente (durata sempre più corta), poi esplosione in sestine discendenti. È la struttura di quasi ogni grande momento di Petrucci: costruzione lenta → detonazione rapida. Il vibrato deve crescere in intensità ad ogni nota — stretto sul 12, ampio sul 19.",
      notes: [
        { string: 1, fret: 12, duration: "h", technique: "~" },
        { string: 1, fret: 15, duration: "q", technique: "~" },
        { string: 1, fret: 17, duration: "q", technique: "~" },
        { string: 1, fret: 19, duration: "h", technique: "~" },
        { string: 1, fret: 17, duration: "16" }, { string: 1, fret: 15, duration: "16" }, { string: 1, fret: 14, duration: "16" },
        { string: 1, fret: 12, duration: "16" }, { string: 1, fret: 15, duration: "16" }, { string: 1, fret: 14, duration: "16" },
        { string: 1, fret: 12, duration: "16" }, { string: 1, fret: 10, duration: "q" },
      ],
    },
    {
      id: "M4.1",
      title: "Approach Notes — frase fusion complessa",
      chapter: "Cap. 4 — Cromatismi e Approach Avanzati",
      sound: "Jazz-fusion sofisticato. Guthrie Govan meets Petrucci.",
      bpm: 88,
      tab: [
        "e|--11h12--14h15b17~--12h13p12--10h11p10--8~--|",
        "B|---------------------------------------------|",
        "G|---------------------------------------------|",
        "D|---------------------------------------------|",
        "A|---------------------------------------------|",
        "E|---------------------------------------------|",
      ],
      tip: "Ogni nota melodica è preceduta da una approach cromatica (semitono sotto). Il risultato è una frase molto più 'jazz' e ricercata. L'approccio cromático funziona su qualsiasi nota della scala — una volta che lo senti nelle dita, inizia ad improvvisarlo.",
      notes: [
        { string: 1, fret: 11, duration: "16" }, { string: 1, fret: 12, duration: "8", technique: "h" },
        { string: 1, fret: 14, duration: "16" }, { string: 1, fret: 15, duration: "16", technique: "h" }, { string: 1, fret: 17, duration: "q", technique: "b~" },
        { string: 1, fret: 12, duration: "16" }, { string: 1, fret: 13, duration: "16", technique: "h" }, { string: 1, fret: 12, duration: "8", technique: "p" },
        { string: 1, fret: 10, duration: "16" }, { string: 1, fret: 11, duration: "16", technique: "h" }, { string: 1, fret: 10, duration: "8", technique: "p" },
        { string: 1, fret: 8, duration: "h", technique: "~" },
      ],
    },
    {
      id: "M4.2",
      title: "Cromatismo ponte — glissata veloce tra posizioni lontane",
      chapter: "Cap. 4 — Cromatismi e Approach Avanzati",
      sound: "Moderno, liquido. Il ponte invisibile tra due idee melodiche.",
      bpm: 95,
      tab: [
        "e|--5-6-7-8-9-10-11-12~--12-11-10-9-8-7-6-5~--|",
        "B|----------------------------------------------|",
        "G|----------------------------------------------|",
        "D|----------------------------------------------|",
        "A|----------------------------------------------|",
        "E|----------------------------------------------|",
      ],
      tip: "Cromatics run: 8 note cromatiche ascendenti, nota lunga, poi 8 discendenti. A 95 BPM in sedicesimi sono esattamente 2 battute. L'obiettivo è che suoni come un glissato pianistico, non come 8 note separate. Tieni l'arcata dinamica: crescendo in salita, diminuendo in discesa.",
      notes: [
        { string: 1, fret: 5, duration: "16" }, { string: 1, fret: 6, duration: "16" }, { string: 1, fret: 7, duration: "16" }, { string: 1, fret: 8, duration: "16" },
        { string: 1, fret: 9, duration: "16" }, { string: 1, fret: 10, duration: "16" }, { string: 1, fret: 11, duration: "16" }, { string: 1, fret: 12, duration: "q", technique: "~" },
        { string: 1, fret: 12, duration: "16" }, { string: 1, fret: 11, duration: "16" }, { string: 1, fret: 10, duration: "16" }, { string: 1, fret: 9, duration: "16" },
        { string: 1, fret: 8, duration: "16" }, { string: 1, fret: 7, duration: "16" }, { string: 1, fret: 6, duration: "16" }, { string: 1, fret: 5, duration: "q", technique: "~" },
      ],
    },
    {
      id: "M5.1",
      title: "Question & Answer — lento vs veloce",
      chapter: "Cap. 5 — Dinamica Avanzata",
      sound: "Narrativo, cinematico. La struttura dell'assolo perfetto.",
      bpm: 0,
      tab: [
        "e|--15~~~--15p12--14b15~--[pausa 2 sec]--|",
        "B|---------------------------------------|",
        "e|--12-15-17-15-12--15-17-19-17-15--17b19~~~--|",
        "B|---------------------------------------------|",
      ],
      tip: "DOMANDA: nota lunga + discesa + bend non risolto (tensione). PAUSA di 2 secondi (obbligatoria). RISPOSTA: frase veloce 3NPC che sale e risolve sul bend finale. La risposta deve essere quasi il doppio della velocità della domanda — il contrasto è il punto. Suona su BT-5.",
      notes: [
        { string: 1, fret: 15, duration: "h", technique: "~" },
        { string: 1, fret: 15, duration: "16", technique: "p" }, { string: 1, fret: 12, duration: "16" },
        { string: 1, fret: 14, duration: "q", technique: "b" },
        { string: 1, fret: 12, duration: "16" }, { string: 1, fret: 15, duration: "16" }, { string: 1, fret: 17, duration: "16" },
        { string: 1, fret: 15, duration: "16" }, { string: 1, fret: 12, duration: "16" },
        { string: 1, fret: 15, duration: "16" }, { string: 1, fret: 17, duration: "16" }, { string: 1, fret: 19, duration: "16" },
        { string: 1, fret: 17, duration: "16" }, { string: 1, fret: 15, duration: "16" },
        { string: 1, fret: 17, duration: "8", technique: "b" }, { string: 1, fret: 19, duration: "h", technique: "~" },
      ],
    },
    {
      id: "M5.2",
      title: "Dinamica estrema — ppp→fff in una frase sola",
      chapter: "Cap. 5 — Dinamica Avanzata",
      sound: "Cinematico, epico. Il climax dell'assolo che ti fa alzare in piedi.",
      bpm: 85,
      tab: [
        "e|--12~(pp)--15~(mp)--17~(mf)----19h22~~~~(fff)--|",
        "B|------------------------------------------------|",
        "G|------------------------------------------------|",
        "D|------------------------------------------------|",
        "A|------------------------------------------------|",
        "E|------------------------------------------------|",
      ],
      tip: "Quattro note con vibrato progressivamente più ampio e forte. pp = quasi inudibile. fff = massimo volume pulito. Il 22° tasto richiede un bend di tono dal 19° — usa 3 dita per il bend. Tieni il 22° (=bend) per 4 secondi con vibrato ampio. Poi silenzio totale. Non aggiungere niente dopo.",
      notes: [
        { string: 1, fret: 12, duration: "q", technique: "~" },
        { string: 1, fret: 15, duration: "q", technique: "~" },
        { string: 1, fret: 17, duration: "q", technique: "~" },
        { string: 1, fret: 19, duration: "16", technique: "h" },
        { string: 1, fret: 22, duration: "w", technique: "~" },
      ],
    },
    {
      id: "M5.3",
      title: "Syncopation avanzata — groove metal su sestine",
      chapter: "Cap. 5 — Dinamica Avanzata",
      sound: "Groove, funk-metal, tensione ritmica massima.",
      bpm: 95,
      tab: [
        "e|--12----15----12-15--12-15-17-15-12-15~--|",
        "B|-----------------------------------------|",
        "G|-----------------------------------------|",
        "D|-----------------------------------------|",
        "A|-----------------------------------------|",
        "E|-----------------------------------------|",
      ],
      tip: "Le note sui trattini sono silenzio — ma devono essere silenzi attivi, non vuoti. Conta internamente anche le note che non suoni. Il pattern anticipa il beat di un sedicesimo ad ogni ripetizione creando tensione crescente. Risolvi sull'ultimo 15~ con vibrato ampio.",
      notes: [
        { string: 1, fret: 12, duration: "8" }, { string: 1, fret: 15, duration: "8" },
        { string: 1, fret: 12, duration: "8" }, { string: 1, fret: 15, duration: "16" }, { string: 1, fret: 12, duration: "16" },
        { string: 1, fret: 15, duration: "16" }, { string: 1, fret: 17, duration: "16" }, { string: 1, fret: 15, duration: "16" },
        { string: 1, fret: 12, duration: "16" }, { string: 1, fret: 15, duration: "q", technique: "~" },
      ],
    },
  ],

  backingTracks: [
    { id: "BT-1", title: "Hard Rock in La minore — veloce", chords: ["Am", "F", "G", "E"], bpm: "110-120", key: "La minore", scale: "La minore naturale, pentatonica La min, La dorico", youtube: "A minor hard rock backing track 120 bpm", months: "Mese 1-2" },
    { id: "BT-2", title: "Progressive Metal in Mi minore", chords: ["Em", "C", "D", "B7"], bpm: "120-130", key: "Mi minore", scale: "Mi minore naturale, Mi frigio, Mi minore armonica", youtube: "E minor progressive metal backing track 120 bpm", months: "Mese 1-2" },
    { id: "BT-3", title: "Fusion veloce in Re minore", chords: ["Dm7", "Bb", "Am7", "E7"], bpm: "130", key: "Re minore", scale: "Re dorico, Re minore naturale, arpeggi Dm/F/Am", youtube: "D minor jazz fusion fast backing track", months: "Mese 2-3" },
    { id: "BT-4", title: "Dream Theater Style — progressivo", chords: ["Am", "Fmaj7", "Dm7", "E7sus4"], bpm: "120", key: "La minore (armonica su E)", scale: "La minore naturale, La minore armonica, sweep arpeggi", youtube: "Dream Theater style backing track A minor", months: "Mese 3-4" },
    { id: "BT-5", title: "Another Day — stile originale", chords: ["Am", "Fmaj7", "Dm7", "E7"], bpm: "85", key: "La minore", scale: "La minore naturale, La minore armonica, arpeggi, sweep", youtube: "A minor progressive rock ballad backing track 85 bpm", months: "Mese 4" },
  ],
};
